bak/routes/web.php
<?php
Route::redirect('/', '/login');

Route::redirect('/home', '/admin');

Auth::routes(['register' => false]);

//Admin
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => ['auth']], function () {

	//Section
	Route::group(['namespace' => 'Section', 'prefix' => 'section', 'as' => 'section.'], function () {
		/*
		 * For DataTables
		 */
		Route::post('get', 'SectionTableController')->name('get');

		/*
		 * CRUD
		 */
		Route::get('/', 'SectionController@index')->name('index');
		Route::get('create', 'SectionController@create')->name('create');
		Route::post('/', 'SectionController@store')->name('store');				

		/*
		 * Specified
		 */
		Route::group(['prefix' => '{section}'], function () {
			Route::get('/edit', 'SectionController@edit')->name('edit');
			Route::patch('/', 'SectionController@update')->name('update');
			Route::delete('/', 'SectionController@delete')->name('delete');
		});
	});
});

//User
Route::group(['middleware' => ['auth']], function () {
	Route::get('/', 'HomeController@index')->name('home');
	
	//Quiz
	Route::group(['prefix' => 'quiz', 'as' => 'quiz.'], function () {
		Route::get('/', 'QuizController@index')->name('index');		
		Route::get('/result', 'QuizController@result')->name('result');
	});
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
	Route::get('/', 'HomeController@index')->name('home');

	Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

	Route::resource('permissions', 'PermissionsController');

	Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

	Route::resource('roles', 'RolesController');

	Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

	Route::resource('users', 'UsersController');

	Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

	Route::resource('products', 'ProductsController');
});

bak/resources/views/partials/breadcrumbs.blade.php
@if($breadcrumbs)
	<ol class="breadcrumb">
		<!-- <li class="breadcrumb-item">
			{{ __('strings.dashboard.title') }}
		</li> -->

		@foreach($breadcrumbs as $breadcrumb)
			@if($breadcrumb->url && !$loop->last)
				<li class="breadcrumb-item"><a href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</a></li>
			@else
				<li class="breadcrumb-item active">{{ $breadcrumb->title }}</li>
			@endif
		@endforeach

		@yield('breadcrumb-links')
	</ol>
@endif

bak/resources/views/partials/menu.blade.php
<div class="sidebar">
	<nav class="sidebar-nav ps ps--active-y">
		<ul class="nav">
			<li class="nav-item">
				<a href="{{ route("admin.home") }}" class="nav-link">
					<i class="nav-icon fas fa-tachometer-alt"></i>
					{{ trans('global.menus.dashboard') }}
				</a>
			</li>

			<li class="nav-item">
				<a href="{{ route("admin.section.index") }}" class="nav-link">
					<i class="nav-icon fas fa-tachometer-alt"></i>
					{{ trans('global.menus.section') }}
				</a>
			</li>

			<li class="nav-item nav-dropdown">
				<a class="nav-link  nav-dropdown-toggle">
					<i class="fas fa-users nav-icon">

					</i>
					{{ trans('global.userManagement.title') }}
				</a>
				<ul class="nav-dropdown-items">
					<li class="nav-item">
						<a href="{{ route("admin.permissions.index") }}" class="nav-link {{ request()->is('admin/permissions') || request()->is('admin/permissions/*') ? 'active' : '' }}">
							<i class="fas fa-unlock-alt nav-icon">

							</i>
							{{ trans('global.permission.title') }}
						</a>
					</li>
					<li class="nav-item">
						<a href="{{ route("admin.roles.index") }}" class="nav-link {{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
							<i class="fas fa-briefcase nav-icon">

							</i>
							{{ trans('global.role.title') }}
						</a>
					</li>
					<li class="nav-item">
						<a href="{{ route("admin.users.index") }}" class="nav-link {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
							<i class="fas fa-user nav-icon">

							</i>
							{{ trans('global.user.title') }}
						</a>
					</li>
				</ul>
			</li>
			<li class="nav-item">
				<a href="{{ route("admin.products.index") }}" class="nav-link {{ request()->is('admin/products') || request()->is('admin/products/*') ? 'active' : '' }}">
					<i class="fas fa-cogs nav-icon">

					</i>
					{{ trans('global.product.title') }}
				</a>
			</li>
			<li class="nav-item">
				<a href="#" class="nav-link" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
					<i class="nav-icon fas fa-sign-out-alt">

					</i>
					{{ trans('global.logout') }}
				</a>
			</li>
		</ul>

		<div class="ps__rail-x" style="left: 0px; bottom: 0px;">
			<div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div>
		</div>
		<div class="ps__rail-y" style="top: 0px; height: 869px; right: 0px;">
			<div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 415px;"></div>
		</div>
	</nav>
	<button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>

bak/resources/views/partials/messages.blade.php
 @if($errors->any())
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>

        @foreach($errors->all() as $error)
            {{ $error }}<br/>
        @endforeach
    </div>
@elseif(session()->get('flash_success'))
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>

        @if(is_array(json_decode(session()->get('flash_success'), true)))
            {{ implode('', session()->get('flash_success')->all(':message<br/>')) }}
        @else
            {{ session()->get('flash_success') }}
        @endif
    </div>
@elseif(session()->get('flash_warning'))
    <div class="alert alert-warning" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>

        @if(is_array(json_decode(session()->get('flash_warning'), true)))
            {{ implode('', session()->get('flash_warning')->all(':message<br/>')) }}
        @else
            {{ session()->get('flash_warning') }}
        @endif
    </div>
@elseif(session()->get('flash_info'))
    <div class="alert alert-info" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>

        @if(is_array(json_decode(session()->get('flash_info'), true)))
            {{ implode('', session()->get('flash_info')->all(':message<br/>')) }}
        @else
            {{ session()->get('flash_info') }}
        @endif
    </div>
@elseif(session()->get('flash_danger'))
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>

        @if(is_array(json_decode(session()->get('flash_danger'), true)))
            {{ implode('', session()->get('flash_danger')->all(':message<br/>')) }}
        @else
            {{ session()->get('flash_danger') }}
        @endif
    </div>
@elseif(session()->get('flash_message'))
    <div class="alert alert-info" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>

        @if(is_array(json_decode(session()->get('flash_message'), true)))
            {{ implode('', session()->get('flash_message')->all(':message<br/>')) }}
        @else
            {{ session()->get('flash_message') }}
        @endif
    </div>
@endif