bak/routes/web.php
<?php
Route::redirect('/', '/login');

Route::redirect('/home', '/admin');

Auth::routes(['register' => false]);

//Admin
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => ['auth']], function () {

	//Section
	Route::group(['namespace' => 'Section', 'prefix' => 'section', 'as' => 'section.'], function () {
		/*
		 * For DataTables
		 */
		Route::post('get', 'SectionTableController')->name('get');

		/*
		 * CRUD
		 */
		Route::get('/', 'SectionController@index')->name('index');
		Route::get('create', 'SectionController@create')->name('create');
		Route::post('/', 'SectionController@store')->name('store');				

		/*
		 * Specified
		 */
		Route::group(['prefix' => '{section}'], function () {
			Route::get('/edit', 'SectionController@edit')->name('edit');
			Route::patch('/', 'SectionController@update')->name('update');
			Route::delete('/', 'SectionController@delete')->name('delete');
		});
	});
});

//User
Route::group(['middleware' => ['auth']], function () {
	Route::get('/', 'HomeController@index')->name('home');
	
	//Quiz
	Route::group(['prefix' => 'quiz', 'as' => 'quiz.'], function () {
		Route::get('/', 'QuizController@index')->name('index');		
		Route::get('/result', 'QuizController@result')->name('result');
	});
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
	Route::get('/', 'HomeController@index')->name('home');

	Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

	Route::resource('permissions', 'PermissionsController');

	Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

	Route::resource('roles', 'RolesController');

	Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

	Route::resource('users', 'UsersController');

	Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

	Route::resource('products', 'ProductsController');
});

bak/app/Models/Section/Section.php
<?php

namespace App\Models\Section;

use Illuminate\Database\Eloquent\Model;
use App\Models\Section\Traits\Attribute\SectionAttribute;

class Section extends Model
{
	use SectionAttribute;
    /**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'title',
		'active'
	];

	protected $dates = [
		'created_at',
		'updated_at',
	];
}

bak/app/Models/Section/Traits/Attribute/SectionAttribute.php
<?php

namespace App\Models\Section\Traits\Attribute;

use Illuminate\Support\Facades\Hash;

/**
 * Trait SectionAttribute.
 */
trait SectionAttribute
{

	/**
	 * @return string
	 */
	public function getEditButtonAttribute()
	{
		return '<a href="' . route('admin.section.edit', $this) . '" class="btn btn-success"><i class="fas fa-edit"></i></a>';
	}
	/**
	 * @return string
	 */
	public function getDeleteButtonAttribute()
	{
		return '<a href="' . route('admin.section.delete', $this) . '" class="btn btn-danger"><i class="fas fa-trash"></i></a>';
	}

	/**
	 * @return string
	 */
	public function getStatusAttribute()
	{
		return ($this->active ? '<i class="text-success fa fa-check fa-lg"></i>' : '<i class="text-danger fa fas fa-times fa-lg"></i>');
	}

	/**
	 * @return string
	 */
	public function getActionButtonsAttribute()
	{
		return '
			<div class="btn-group" role="group">
				' . $this->edit_button . $this->delete_button . '
			</div>';
	}
}

bak/app/Http/Controllers/Admin/Section/SectionController.php
<?php

namespace App\Http\Controllers\Admin\Section;

use App\Http\Controllers\Controller;
use App\Http\Requests\Section\ManageSectionRequest;
use App\Http\Requests\Section\UpdateSectionRequest;
use App\Repositories\SectionRepository;
use App\Models\Section\Section;

class SectionController extends Controller
{

	/**
	 * @var SectionRepository
	 */
	protected $sectionRepository;

	/**
	 * SectionController constructor.
	 *
	 * @param SectionRepository $sectionRepository
	 */
	public function __construct(SectionRepository $sectionRepository)
	{
		$this->sectionRepository = $sectionRepository;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		return view('admin.sections.index');
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('admin.sections.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(ManageSectionRequest $request)
	{
		$this->sectionRepository->create($request->only(
			'title',
			'active'
		));

		return redirect()->route('admin.section.index')->withFlashSuccess(__('alerts.sections.created'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit(Section $section)
	{
		return view('admin.sections.edit')
			->withSection($section);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(UpdateSectionRequest $request, Section $section)
	{
		$this->sectionRepository->update($section, $request->only(
			'title',
			'active'
		));

		return redirect()->route('admin.section.index')->withFlashSuccess(__('alerts.sections.updated'));
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		//
	}
}

bak/app/Http/Controllers/Admin/Section/SectionTableController.php
<?php

namespace App\Http\Controllers\Admin\Section;

use App\Http\Controllers\Controller;
use App\Http\Requests\Section\ManageSectionRequest;
use App\Repositories\SectionRepository;
use DataTables;

/**
 * Class SectionTableController.
 */
class SectionTableController extends Controller
{	
	/**
	 * @var $sectionRepository
	 */
	protected $sectionRepository;

	/**
	 * SectionTableController constructor.
	 *
	 * @param SectionRepository $sectionRepository
	 */
	public function __construct(SectionRepository $sectionRepository)
	{
		$this->sectionRepository = $sectionRepository;
	}

	/**
	 * @param ManageSectionRequest $request
	 *
	 * @return mixed
	 */
	public function __invoke(ManageSectionRequest $request)
	{

		return Datatables::of($this->sectionRepository->getForDataTable())
			->addColumn('index_column', function ($section){
				return '';
			})
			->addColumn('active', function ($section){
				return $section->status;
			})
			->addColumn('actions', function ($section){
				return $section->action_buttons;
			})
			->rawColumns(['active', 'actions'])
			->make(true);
	}

}

bak/resources/views/admin/sections/create.blade.php
@extends('layouts.admin')
@section('content')
<form method="POST" action="{{ route('admin.section.store') }}">
    @csrf
	<div class="card">
		<div class="card-header">
			<h4>{{ trans('strings.sections.title') }}<small class="text-muted"> 
			| {{ trans('strings.sections.create') }}</small></h4>
		</div>

		<div class="card-body">
			<div class="row">
				<div class="col-sm-6">
					<div class="form-group">
						<label for="title">{{ __('validation.attributes.title') }}</label>
						<input class="form-control" name="title" id="title" type="text" placeholder="{{ __('validation.attributes.title') }}">
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label for="title" class="d-block">{{ __('validation.attributes.active') }}</label>
						
						<div class="d-flex">
							<label class="m-2">{{ __('strings.close') }}</label>
							<label class="switch switch-pill switch-lg switch-success">
								<input type="checkbox" name="active" class="switch-input" checked>
								<span class="switch-slider"></span>
							</label>
							<label class="m-2">{{ __('strings.open') }}</label>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="card-footer">
			<div class="row">
				<div class="col text-right">
					<a class="btn btn-danger" href="{{ route('admin.section.index') }}"><i class="fas fa-ban"></i> {{ __('buttons.cancel') }}</a>
					<button type="submit" class="btn btn-success"><i class="fas fa-save"></i> {{ __('buttons.crud.save') }}</button>
				</div>
			</div>
		</div>
	</div>
</form>
@endsection

bak/resources/views/admin/sections/edit.blade.php
@extends('layouts.admin')

@section('content')
<form method="POST" action="{{ route('admin.section.update', ['section' => $section]) }}">
	@csrf
	@method('PATCH')
	<div class="card">
		<div class="card-header">
			<h4>{{ trans('strings.sections.title') }}<small class="text-muted"> 
			| {{ trans('strings.edit') }}</small></h4>
		</div>

		<div class="card-body">
			<div class="row">
				<div class="col-sm-6">
					<div class="form-group">
						<label for="title">{{ __('validation.attributes.title') }}</label>
						<input class="form-control" name="title" id="title" value="{{ $section->title }}" type="text" placeholder="{{ __('validation.attributes.title') }}">
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label for="title" class="d-block">{{ __('validation.attributes.active') }}</label>
						
						<div class="d-flex">
							<label class="m-2">{{ __('strings.close') }}</label>
							<label class="switch switch-pill switch-lg switch-success">
								<input type="checkbox" name="active" class="switch-input" {{ ($section->active ? "checked" : "") }}>
								<span class="switch-slider"></span>
							</label>
							<label class="m-2">{{ __('strings.open') }}</label>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="card-footer">
			<div class="row">
				<div class="col text-right">
					<a class="btn btn-danger" href="{{ route('admin.section.index') }}"><i class="fas fa-ban"></i> {{ __('buttons.cancel') }}</a>
					<button type="submit" class="btn btn-success"><i class="fas fa-save"></i> {{ __('buttons.crud.save') }}</button>
				</div>
			</div>
		</div>
	</div>
</form>
@endsection

bak/resources/views/admin/sections/index.blade.php
@extends('layouts.admin')

@push('before-styles')
	<link href="{{ asset('plugins/datatables/jquery.dataTables.min.css') }}" rel="stylesheet" />
	<link href="{{ asset('plugins/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" />
@endpush

@section('content')
<div class="card">
	<div class="card-body">
		<div class="row">
			<div class="col-sm-5">
				<h4 class="card-title mb-0">
					{{ __('labels.letters.management') }} <small class="text-muted">{{ __('labels.letters.local') }}</small>
				</h4>
			</div>

			<div class="col-sm-7">
				<div class="btn-toolbar float-right" role="toolbar" aria-label="@lang('labels.general.toolbar_btn_groups')">
					<a href="{{ route('admin.section.create') }}" class="btn btn-success btn-min ml-1"><i class="fas fa-plus-circle"></i> @lang('buttons.crud.create_new')</a>
				</div>
			</div>
		</div>

		<div class="mt-4">
			<table class="table table-bordered table-striped table-hover dt-responsive nowrap" id="master-table">
				<thead>
					<tr class="text-center">
						<th class="numberic">#</th>
						<th>{{ __('strings.sections.table.title') }}</th>
						<th>{{ __('strings.sections.table.active') }}</th>
						<th>{{ __('strings.sections.table.action') }}</th>
					</tr>
				</thead>
				<tbody class="text-center"></tbody>
			</table>
		</div>
	</div>
</div>
@endsection

@push('scripts')
	<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
	<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>

	<script>
		var _url = "{{ route('admin.section.get') }}";
		var _columns = [
			{data: 'index_column', name: 'index_column', searchable: false, sortable: false, class: 'text-center'},
			{data: 'title'},
			{data: 'active', searchable: false, sortable: false, class: 'text-center'},
			{data: 'actions', searchable: false, sortable: false, class: 'text-center'}
		];

		$(function () {
			
			// var _columns = [
			// 	{data: 'index_column', name: 'index_column', searchable: false, sortable: false, class: 'text-center'}
			// ];

			// var _mission = $('#mission-table').DataTable({
			// 	processing: true,
			// 	searching: true,
			// 	serverSide: true,
			// 	pageLength: 25,
			// 	ajax: {
			// 		url: '{{ route("admin.section.get") }}',
			// 		type: "GET",
			// 	},
			// 	// language: {
			// 	// 	url: '{{ asset('plugins/datatables/i18n/kh.lang') }}',
			// 	// },
			// 	columns: _columns,
			// 	order: [[ 1, 'asc' ]],
			// });
		});
	</script>
@endpush